function SfxrParams(){this.setSettings=function(a){for(var b=0;24>b;b++)this[String.fromCharCode(97+b)]=a[b]||0;.01>this.c&&(this.c=.01);a=this.b+this.c+this.e;.18>a&&(a=.18/a,this.b*=a,this.c*=a,this.e*=a)}}
function SfxrSynth(){this._params=new SfxrParams;var a,b,c,d,e,g,n,p,m,r,v,h;this.reset=function(){var a=this._params;d=100/(a.f*a.f+.001);e=100/(a.g*a.g+.001);g=1-a.h*a.h*a.h*.01;n=-a.i*a.i*a.i*1E-6;a.a||(v=.5-a.n/2,h=5E-5*-a.o);p=1+a.l*a.l*(0<a.l?-.9:10);m=0;r=1==a.m?0:(1-a.m)*(1-a.m)*2E4+32};this.totalReset=function(){this.reset();var g=this._params;a=g.b*g.b*1E5;b=g.c*g.c*1E5;c=g.e*g.e*1E5+12;return 3*((a+b+c)/3|0)};this.synthWave=function(x,y){var f=this._params,u=1!=f.s||f.v,t=f.v*f.v*.1,z=
1+3E-4*f.w,k=f.s*f.s*f.s*.1,w=1+1E-4*f.t,B=1!=f.s,L=f.x*f.x,aa=f.g,S=f.q||f.r,ba=f.r*f.r*f.r*.2,T=f.q*f.q*(0>f.q?-1020:1020),U=f.p?((1-f.p)*(1-f.p)*2E4|0)+32:0,ca=f.d,V=f.j/2,da=f.k*f.k*.01,O=f.a,P=a,ea=1/a,fa=1/b,ha=1/c;f=5/(1+f.u*f.u*20)*(.01+k);.8<f&&(f=.8);f=1-f;for(var Q=!1,W=0,G=0,H=0,X=0,M=0,I,J=0,A,D=0,E,R=0,q,Y=0,F,Z=0,N=Array(1024),K=Array(32),C=N.length;C--;)N[C]=0;for(C=K.length;C--;)K[C]=2*Math.random()-1;for(C=0;C<y;C++){if(Q)return C;U&&++Y>=U&&(Y=0,this.reset());r&&++m>=r&&(r=0,d*=
p);g+=n;d*=g;d>e&&(d=e,0<aa&&(Q=!0));A=d;0<V&&(Z+=da,A*=1+Math.sin(Z)*V);A|=0;8>A&&(A=8);O||(v+=h,0>v?v=0:.5<v&&(v=.5));if(++G>P)switch(G=0,++W){case 1:P=b;break;case 2:P=c}switch(W){case 0:H=G*ea;break;case 1:H=1+2*(1-G*fa)*ca;break;case 2:H=1-G*ha;break;case 3:H=0,Q=!0}S&&(T+=ba,E=T|0,0>E?E=-E:1023<E&&(E=1023));u&&z&&(t*=z,1E-5>t?t=1E-5:.1<t&&(t=.1));F=0;for(var ia=8;ia--;){D++;if(D>=A&&(D%=A,3==O))for(I=K.length;I--;)K[I]=2*Math.random()-1;switch(O){case 0:q=D/A<v?.5:-.5;break;case 1:q=1-D/A*2;
break;case 2:q=D/A;q=6.28318531*(.5<q?q-1:q);q=1.27323954*q+.405284735*q*q*(0>q?1:-1);q=.225*((0>q?-1:1)*q*q-q)+q;break;case 3:q=K[Math.abs(32*D/A|0)]}u&&(I=J,k*=w,0>k?k=0:.1<k&&(k=.1),B?(M+=(q-J)*k,M*=f):(J=q,M=0),J+=M,X+=J-I,q=X*=1-t);S&&(N[R%1024]=q,q+=N[(R-E+1024)%1024],R++);F+=q}F*=.125*H*L;x[C]=1<=F?32767:-1>=F?-32768:32767*F|0}return y}}var synth=new SfxrSynth;
window.jsfxr=function(a){synth._params.setSettings(a);var b=synth.totalReset();a=new Uint8Array(4*((b+1)/2|0)+44);b=2*synth.synthWave(new Uint16Array(a.buffer,44),b);var c=new Uint32Array(a.buffer,0,44);c[0]=1179011410;c[1]=b+36;c[2]=1163280727;c[3]=544501094;c[4]=16;c[5]=65537;c[6]=44100;c[7]=88200;c[8]=1048578;c[9]=1635017060;c[10]=b;b+=44;c=0;for(var d="data:audio/wav;base64,";c<b;c+=3){var e=a[c]<<16|a[c+1]<<8|a[c+2];d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[e>>18]+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[e>>12&63]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[e>>6&63]+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[e&63]}return d};var sonantx;
(function(){function a(a){return Math.sin(6.283184*a)}function b(a,c){setTimeout(function(){var g=new Uint8Array(4*a),b=g.length-2,n=function(){for(var a=new Date,p=0;0<=b;)if(g[b]=0,g[b+1]=128,b-=2,p+=1,0===p%1E3&&33<new Date-a){setTimeout(n,0);return}setTimeout(function(){c(g)},0)};setTimeout(n,0)},0)}function c(a,b,c,m,d){var g=c.fx_delay_time*m>>1,n=c.fx_delay_amt/255,p=0,e=function(){for(var c=new Date,m=0;p<b-g;){var r=4*p,h=4*(p+g),k=a[h]+(a[h+1]<<8)+(a[r+2]+(a[r+3]<<8)-32768)*n;a[h]=k&255;
a[h+1]=k>>8&255;k=a[h+2]+(a[h+3]<<8)+(a[r]+(a[r+1]<<8)-32768)*n;a[h+2]=k&255;a[h+3]=k>>8&255;++p;m+=1;if(0===m%1E3&&33<new Date-c){setTimeout(e,0);return}}setTimeout(d,0)};setTimeout(e,0)}sonantx={};var d=null,e=[a,function(c){return 0>a(c)?-1:1},function(a){return a%1-.5},function(a){a=a%1*4;return 2>a?a-1:3-a}];sonantx.AudioGenerator=function(a){this.mixBuf=a;this.waveSize=a.length/2/2};sonantx.AudioGenerator.prototype.getWave=function(){var a=this.mixBuf,c=4*this.waveSize;var b=c-8;var m=b-36;
var e=String.fromCharCode(82,73,70,70,b&255,b>>8&255,b>>16&255,b>>24&255,87,65,86,69,102,109,116,32,16,0,0,0,1,0,2,0,68,172,0,0,16,177,2,0,4,0,16,0,100,97,116,97,m&255,m>>8&255,m>>16&255,m>>24&255);for(b=0;b<c;){var d="";for(m=0;256>m&&b<c;++m,b+=2){var h=4*(a[b]+(a[b+1]<<8)-32768);h=-32768>h?-32768:32767<h?32767:h;d+=String.fromCharCode(h&255,h>>8&255)}e+=d}return e};sonantx.AudioGenerator.prototype.getAudio=function(){var a=this.getWave();a=new Audio("data:audio/wav;base64,"+btoa(a));a.preload=
"none";a.load();return a};sonantx.AudioGenerator.prototype.getAudioBuffer=function(a){null===d&&(d=new AudioContext);var b=this.mixBuf,c=this.waveSize,g=d.createBuffer(2,this.waveSize,44100),e=g.getChannelData(0),v=g.getChannelData(1),h=0,x=function(){for(var n=new Date,f=0;h<c;){var d=4*(b[4*h]+(b[4*h+1]<<8)-32768);d=-32768>d?-32768:32767<d?32767:d;e[h]=d/32768;d=4*(b[4*h+2]+(b[4*h+3]<<8)-32768);d=-32768>d?-32768:32767<d?32767:d;v[h]=d/32768;h+=1;f+=1;if(0===f%1E3&&33<new Date-n){setTimeout(x,0);
return}}setTimeout(function(){a(g)},0)};setTimeout(x,0)};sonantx.SoundGenerator=function(a,b){this.instr=a;this.rowLen=b||5605;this.osc_lfo=e[a.lfo_waveform];this.osc1=e[a.osc1_waveform];this.osc2=e[a.osc2_waveform];this.attack=a.env_attack;this.sustain=a.env_sustain;this.release=a.env_release;this.panFreq=Math.pow(2,a.fx_pan_freq-8)/this.rowLen;this.lfoFreq=Math.pow(2,a.lfo_freq-8)/this.rowLen};sonantx.SoundGenerator.prototype.genSound=function(b,c,d){var g=0,e=0,n=.00390625*Math.pow(1.059463094,
b+12*(this.instr.osc1_oct-8)+this.instr.osc1_det-128)*(1+8E-4*this.instr.osc1_detune);b=.00390625*Math.pow(1.059463094,b+12*(this.instr.osc2_oct-8)+this.instr.osc2_det-128)*(1+8E-4*this.instr.osc2_detune);for(var p=this.instr.fx_resonance/255,x=0,y=0,f=this.attack+this.sustain+this.release-1;0<=f;--f){var u=f+d,t=this.osc_lfo(u*this.lfoFreq)*this.instr.lfo_amt/512+.5,z=1;f<this.attack?z=f/this.attack:f>=this.attack+this.sustain&&(z-=(f-this.attack-this.sustain)/this.release);var k=n;this.instr.lfo_osc1_freq&&
(k+=t);this.instr.osc1_xenv&&(k*=z*z);g+=k;var w=this.osc1(g)*this.instr.osc1_vol;k=b;this.instr.osc2_xenv&&(k*=z*z);e+=k;w+=this.osc2(e)*this.instr.osc2_vol;this.instr.noise_fader&&(w+=(2*Math.random()-1)*this.instr.noise_fader*z);w*=z/255;k=this.instr.fx_freq;this.instr.lfo_fx_freq&&(k*=t);k=1.5*Math.sin(3.141592*k/44100);x+=k*y;t=p*(w-y)-x;y+=k*t;switch(this.instr.fx_filter){case 1:w=t;break;case 2:w=x;break;case 3:w=y;break;case 4:w=x+t}k=a(u*this.panFreq)*this.instr.fx_pan_amt/512+.5;w*=39*this.instr.env_master;
u*=4;u+3<c.length&&(t=c[u]+(c[u+1]<<8)+w*(1-k),c[u]=t&255,c[u+1]=t>>8&255,t=c[u+2]+(c[u+3]<<8)+w*k,c[u+2]=t&255,c[u+3]=t>>8&255)}};sonantx.SoundGenerator.prototype.getAudioGenerator=function(a,d){var g=this.attack+this.sustain+this.release-1+32*this.rowLen,e=this;b(g,function(b){e.genSound(a,b,0);c(b,g,e.instr,e.rowLen,function(){d(new sonantx.AudioGenerator(b))})})};sonantx.SoundGenerator.prototype.createAudio=function(a,b){this.getAudioGenerator(a,function(a){b(a.getAudio())})};sonantx.SoundGenerator.prototype.createAudioBuffer=
function(a,b){this.getAudioGenerator(a,function(a){a.getAudioBuffer(b)})};sonantx.MusicGenerator=function(a){this.song=a;this.waveSize=44100*a.songLen};sonantx.MusicGenerator.prototype.generateTrack=function(a,d,e){var g=this;b(this.waveSize,function(b){var n=g.waveSize,h=4*g.waveSize,m=g.song.rowLen,p=g.song.endPattern,f=new sonantx.SoundGenerator(a,m),u=0,t=0,r=0,k=function(){for(var c=new Date;;)if(32===r)r=0,t+=1;else{if(t===p-1){setTimeout(w,0);break}var d=a.p[t];d&&(d=a.c[d-1].n[r])&&f.genSound(d,
b,u);u+=m;r+=1;if(33<new Date-c){setTimeout(k,0);break}}},w=function(){c(b,n,a,m,L)},B=0,L=function(){for(var a=new Date,c=0;B<h;){var f=d[B]+(d[B+1]<<8)+b[B]+(b[B+1]<<8)-32768;d[B]=f&255;d[B+1]=f>>8&255;B+=2;c+=1;if(0===c%1E3&&33<new Date-a){setTimeout(L,0);return}}setTimeout(e,0)};setTimeout(k,0)})};sonantx.MusicGenerator.prototype.getAudioGenerator=function(a){var c=this;b(this.waveSize,function(b){var d=0,e=function(){d<c.song.songData.length?(d+=1,c.generateTrack(c.song.songData[d-1],b,e)):a(new sonantx.AudioGenerator(b))};
e()})};sonantx.MusicGenerator.prototype.createAudio=function(a){this.getAudioGenerator(function(b){a(b.getAudio())})};sonantx.MusicGenerator.prototype.createAudioBuffer=function(a){this.getAudioGenerator(function(b){b.getAudioBuffer(a)})}})();function randomRange(a,b){return Math.floor(Math.random()*(b-a))+a}function pause(a,b){setTimeout(a.bind(this),b)}function rd(a){return Math.round(a)}function css(a,b){for(var c in b)a.style[c]=b[c]}
function create(a,b){var c=document.createElement(a);b&&c.setAttribute("id",b);return c}function remove(a){a.parentNode.removeChild(a)}function $(a){return document.getElementById(a)}
var DHTMLSprite=function(a){var b=a.w,c=a.h,d=a.iW,e=a.t.appendChild(create("div")),g=e.style,n=Math.floor,p=[],m=[],r=0,v=0,h=0,x=0;css(e,{position:"absolute",left:"-9999px",width:b+"px",height:c+"px",backgroundImage:"url("+a.img+")"});var y={diff:function(a,b){r=a;v=b},aA:function(a){p=a},dw:function(a,b){g.left=a+"px";g.top=b+"px"},bI:function(a){x=a;y.cI(x)},cI:function(a){a*=b;var e=-n(a/d)*c;g.backgroundPosition=-a%d+"px "+e+"px"},cA:function(a){p[a]&&(m=p[a])},i:function(){return x},sh:function(){g.display=
"block"},hi:function(){g.display="none"},k:function(){remove(e)},mv:function(a,b){a&&(y.cI(x+m[n(h)]),h+=a/1E3*p.v,h>=m.length&&(h=0))},v:function(){return p.v},dxy:function(){return[r/500,v/500]}};return y},EVT_PLAYER_ENDED_MOVE=0,EVT_ENEMY_ENDED_MOVE=1,STATE_TITLE_SCREEN=2,STATE_PLAYING=3,STATE_STANDBY=4,STATE_INITIALIZATION=5,EVT_PLAYER_DAMAGE=6,STATE_GAMEOVER=7,EVT_WALL_DESTROYED=8,STATE_INIT_MUSIC=9,INIT_LEVEL=1,storyline="Scavenge for survival;Oops. I am not alone;Obstacles are the key;Nude ones are short sighted;I can destroy obstacles too;Brown jackets are trouble;Each move counts;Harder than I thought;I hate Zetas;It's a long way to the top".split(";"),
categories="Burguer meat;Zombie fodder;Novice;Inexperienced;Second rate;Mediocre;Handy;Skilled;Old timer;Veteran;Seasoned pro;Superb;Outstanding;Master".split(";"),SYS_spriteParams={w:32,h:32,iW:256,img:"s3.png",t:$("screen")},columns=8,rows=8,level=2,screen,score,title,oldTime,floorTiles=[31],wallTiles=[25,26,27,28,29,30],outerWallTiles=[21,22,23,24],foodTiles=[18,19],enemyTiles=[6,12],enemyHit=[20,30],enemyAI=[3,4],board=[],objects=[],enemies=[],gridPositions=[],player,detection,enemiesToMove=[],
initialEnergy=25,currentEnergy,maxEnergy,isPlayerMoving=!1,isPlayerTurn=!0,isPlayerDetectedBy=null,isEnemyMoving=!1,animating=!1,gameIsOver=!1,gameState=STATE_INIT_MUSIC,FRUIT_ENERGY=12,SODA_ENERGY=20,soundLib=[],raf=window.requestAnimationFrame,sounds=[[2,.0266,.5034,.5728,.5999,.5026,,-.0108,-.4073,,,,,.543,.7178,.7558,,.9082,.9809,.1312,-.4545,.0055,.0025,.4],[3,.14,.31,.0939,.47,.03,.0071,-.1999,.34,.24,.0685,-.28,,.0233,-.0799,,.0104,.4403,.27,.02,.21,.12,-.18,.32],[3,,.35,.53,.2582,.1909,,.2963,
,,,,,,,,.3,-.0396,1,,,,,.18],[0,,.0878,,.4572,.2507,,.2093,,.1437,.3611,,,.5666,,,,,1,,,,,.3],[0,.34,.26,.24,.23,,,.1232,.1466,.24,1,.9299,,,-1,1,-.8,-.04,.33,-.02,,,-1,.36],[3,.0171,.9078,.3427,.4125,.5181,.0587,-.1099,.484,.0317,.4421,-.4199,.5661,.049,.0066,.2124,-.8404,-.1955,.3985,-.0415,,.0212,-.0439,.32]];function initSound(){sounds.forEach(function(a,b){var c=jsfxr(a),d=new Audio;d.src=c;soundLib.push(d)})}
function init(){gridPositions=[];for(var a=1;a<columns-1;a++)for(var b=1;b<rows-1;b++)(1!=a&&2!=a||6!=b)&&(1!=a&&2!=a||7!=b)&&(0!=a&&1!=a&&2!=a||5!=b)&&gridPositions.push([a,b]);board=[];enemies=[];object=[];b=$("screen").children;a=0;for(l=b.length;a<l;a++)b[a]&&b[a].parentNode&&b[a].parentNode.removeChild(b[a]);for(a=-1;a<columns+1;a++)for(b=-1;b<rows+1;b++){var c=DHTMLSprite(SYS_spriteParams);c.bI(floorTiles[randomRange(0,floorTiles.length)]);-1!==a&&a!==columns&&-1!==b&&b!==rows||c.bI(outerWallTiles[randomRange(0,
outerWallTiles.length)]);board.push([c,a,b,"t"])}a=DHTMLSprite(SYS_spriteParams);a.bI(20);board.push([a,columns-1,0]);objects=layoutObjectsAtRandom(wallTiles,5,10,"w");objects=objects.concat(layoutObjectsAtRandom(foodTiles,1,5,"f"));a=Math.log2(level)|0;enemies=layoutObjectsAtRandom(enemyTiles,a,a,"e",{i:[0,1,2,3,4,5],a:[28,29],v:4});a=DHTMLSprite(SYS_spriteParams);a.cI(0);a.aA({i:[0,1,2,3,4,5],a:[32,33],d:[38,39],v:6});a.cA("i");player=[a,0,rows-1,"p"];screen=$("screen");score=create("div","score");
score.innerHTML="<p>energy: "+currentEnergy+"</p>";screen.appendChild(score);score.update=function(){score.innerHTML="<p>energy: "+currentEnergy+"</p>"}}function drawItem(a){a[0].dw((a[1]+1)*SYS_spriteParams.w,(a[2]+1)*SYS_spriteParams.h)}function launchDetectIcon(){var a=DHTMLSprite(SYS_spriteParams);a.bI(46);a.aA({i:[1,0],v:8});a.cA("i");detection=[a,player[1]+.5,player[2]-.5,"!"];pause(function(){detection[0].k();detection=null},1E3);soundLib[0].play()}
function layoutObjectsAtRandom(a,b,c,d,e){b=randomRange(b,c+1);c=[];for(var g=0;g<b;g++){var n=randomPosition(),p=DHTMLSprite(SYS_spriteParams),m=randomRange(0,a.length),r=a[m];p.bI(r);if("e"!==d)m=[p,n[0],n[1],d,2],"f"===d&&(m[4]=19===r?FRUIT_ENERGY:SODA_ENERGY),c.push(m);else{var v=Object.assign({},e);12==r&&(v.a=[24,25]);p.aA(v);p.cA("i");n=[p,n[0],n[1],d];if(6==r||12==r)n[4]=enemyHit[m],n[5]=enemyAI[m];n[3]=d;c.push(n)}}return c}
function attemptMove(a,b){var c=a[1];"r"==b&&c++;"l"==b&&c--;var d=a[2];"u"==b&&d--;"d"==b&&d++;for(var e=0;e<enemies.length;e++)if(enemies[e][1]==c&&enemies[e][2]==d&&"f"!==enemies[e][3])return"n";for(e=0;e<objects.length;e++)if(objects[e][1]==c&&objects[e][2]==d)return objects[e];return player[1]==c&&player[2]==d?player:"y"}function damage(a){a[4]--;1==a[4]&&a[0].cI(a[0].i()+15);0>=a[4]&&(a[3]="r",a[0].k(),gameCallback(EVT_WALL_DESTROYED))}
function doAnimate(a,b){animating=!0;var c=attemptMove(a,b);if("n"===c)endCharacterMove(a);else if("w"===c[3]||"p"===c[3]){if("p"===c[3]){c[0].cA("d");gameCallback(EVT_PLAYER_DAMAGE,a[4]);var d=!0;soundLib[1].play()}if("w"===c[3]){var e=randomRange(1,4);if(isPlayerDetectedBy!=a&&2>e){endCharacterMove(a);return}damage(c);soundLib[2].play()}a[0].cA("a");pause(function(){a[0].cA("i");d&&c[0].cA("i");endCharacterMove(a)},500)}else{e=a[1];var g=a[2];switch(b){case "l":0<a[1]&&(e--,a[0].diff(-1,0),playWalkSound());
break;case "r":a[1]<columns-1&&(e++,a[0].diff(1,0),playWalkSound());break;case "u":0<a[2]&&(g--,a[0].diff(0,-1),playWalkSound());break;case "d":a[2]<rows-1&&(g++,a[0].diff(0,1),playWalkSound())}endCharacterMove(a,e,g)}}function playWalkSound(){soundLib[4].play()}function randomPosition(){var a=randomRange(0,gridPositions.length);return gridPositions.splice(a,1)[0]}
function decideMovement(a){var b=["l","r","u","d"],c="";Math.abs(a[1]-player[1])+Math.abs(a[2]-player[2])<=a[5]?(detection||isPlayerDetectedBy||(isPlayerDetectedBy=a,launchDetectIcon()),a[2]>player[2]?c="u":a[2]<player[2]&&(c="d"),""===c&&(a[1]>player[1]?c="l":a[1]<player[1]&&(c="r"))):(c=b[randomRange(0,b.length)],isPlayerDetectedBy==a&&(isPlayerDetectedBy=null));doAnimate(a,c)}
function checkCurrentTile(){objects.forEach(function(a,b){if(a[1]===player[1]&&a[2]===player[2])return currentEnergy+=a[4],soundLib[3].play(),objects.splice(b,1),a[0].k(),!1});if(player[1]===columns-1&&0===player[2])return!0}function checkMaxEnergy(){maxEnergy<currentEnergy&&(maxEnergy=currentEnergy)}function checkGameOver(){0>=currentEnergy&&(gameIsOver=!0,gameState=STATE_GAMEOVER)}
function gameLoop(){var a=+new Date,b=a-oldTime;oldTime=a;switch(gameState){case STATE_INIT_MUSIC:title.innerHTML="<p>ROGUE SCAVENGER 13K</p>";screen.style.display="none";title.style.display="block";raf(gameLoop);return;case STATE_INITIALIZATION:gameIsOver=!1;isPlayerDetectedBy=null;currentEnergy=maxEnergy=initialEnergy;level=INIT_LEVEL;init();gameState=STATE_TITLE_SCREEN;break;case STATE_PLAYING:if(isPlayerTurn&&!isPlayerMoving)checkMaxEnergy(),checkGameOver(),handleKeys();else if(!isPlayerTurn&&
!isEnemyMoving){var c=enemiesToMove.pop();c?(pause(function(){decideMovement(c)},250),isEnemyMoving=!0):isPlayerTurn=!0}break;case STATE_TITLE_SCREEN:var d=window.speechSynthesis;pause(function(){var a=d.getVoices(),b=0;a.forEach(function(a,c){0<=a.lang.indexOf("en")&&"Google UK English Male"==a.name&&(b=c)});var c=new SpeechSynthesisUtterance("Day "+level+". "+(storyline[level-1]||""));c.voice=a[b];c.pitch=.5;c.rate=.8;d.speak(c)},500);title.innerHTML="<p>DAY "+level+".</p><p class='small'>"+(storyline[level-
1]||"")+"</p>";screen.style.display="none";title.style.display="block";gameState=STATE_STANDBY;pause(function(){init();screen.style.display="block";title.style.display="none";gameState=STATE_PLAYING},2500);break;case STATE_GAMEOVER:a=level>=l?categories[l-1]:categories[level]||categories[0],title.innerHTML="<p>You DIED</p><p class='small'>of starvation after "+level+" days.<br/>You managed to have "+maxEnergy+" food.<br/>"+a+" scavenger.<br/><a href='https://twitter.com/intent/tweet?url=http://www.js13kgames.com/rogue-scavenger13k&text="+
("I died of starvation after "+level+" days of zombie apocalypse. I am a "+a+" scavenger.")+" #js13k #scavenger13k' target='_blank'>TWEET IT!</a></p>",screen.style.display="none",title.style.display="block",gameState=STATE_STANDBY}updateLoop(b);drawLoop();raf(gameLoop)}
function gameCallback(a,b){switch(a){case EVT_PLAYER_ENDED_MOVE:currentEnergy--;checkCurrentTile()?(isPlayerTurn=!0,isPlayerMoving=!1,isPlayerDetectedBy=null,soundLib[5].play(),pause(function(){level++;gameState=STATE_TITLE_SCREEN},1E3)):pause(function(){isPlayerMoving=isPlayerTurn=!1;enemiesToMove=enemies.slice(0)},250);score.update();break;case EVT_ENEMY_ENDED_MOVE:isEnemyMoving=!1;break;case EVT_PLAYER_DAMAGE:currentEnergy-=b;score.update();break;case EVT_WALL_DESTROYED:for(var c=0;c<objects.length;c++)if("r"===
objects[c][3]){objects.splice(c,1);break}}}function updateLoop(a){player[0].mv(a);if(animating){var b=player[0].dxy();player[1]+=b[0]*a;player[2]+=b[1]*a}enemies.forEach(function(b){b[0].mv(a);if(animating){var c=b[0].dxy();b[1]+=c[0]*a;b[2]+=c[1]*a}});detection&&detection[0].mv(a)}function handleKeys(){isPlayerMoving=!0;keys[0]?doAnimate(player,"l"):keys[2]?doAnimate(player,"r"):keys[1]?doAnimate(player,"u"):keys[3]?doAnimate(player,"d"):isPlayerMoving=!1}
function endCharacterMove(a,b,c){pause(function(){animating=!1;a[0].diff(0,0);b&&(a[1]=b);c&&(a[2]=c);a[1]=rd(a[1]);a[2]=rd(a[2]);"p"==a[3]?gameCallback(EVT_PLAYER_ENDED_MOVE):gameCallback(EVT_ENEMY_ENDED_MOVE)},500)}function drawLoop(){board.forEach(drawItem);objects.forEach(drawItem);enemies.forEach(drawItem);drawItem(player);detection&&drawItem(detection)}function switchMusic(){gainNode.gain.value=-1==gainNode.gain.value?-.84:-1}var keys=[0,0,0,0];
document.onkeyup=document.onkeydown=function(a){a.preventDefault();var b=a.keyCode-37;"keyup"==a.type?(keys[b]=0,40==b&&switchMusic()):keys[b]=1;gameIsOver&&pause(gameState=STATE_INITIALIZATION,1E3)};title=$("title");screen=$("screen");pause(function(){initSound();gameState=STATE_INITIALIZATION},500);gameLoop();